### ISSUE TITLE
cat > keys.txt empties "keys.txt"

### ISSUE THREAD

**Issue by kootenpv** [google/sshkey-audit#1]
Probably you mean: `cat keys.txt`

**Comment by ThomasHabets** [comment]
I didn't mean that, no. It's example instructions to set up (including the `^D` to signal EOF), not to see how it's set up.

But maybe it should be just `cat`, to show what *was* written.

Is there an established standard for this? Maybe the latter is more common?

**Comment by kootenpv** [comment]
I think if you have a way to generate it with a command, you would show
that.

If not, then show the input you expect... that can indeed be done with `cat
keys.txt`

Thats my take on it :)
